# Generated by Django 3.0.3 on 2020-05-09 03:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('series', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
                ('isbn10', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('isbn13', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('pages', models.IntegerField()),
                ('size', models.CharField(max_length=10)),
                ('format', models.CharField(max_length=10)),
                ('md5', models.CharField(max_length=32)),
                ('sha256', models.CharField(max_length=64)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('thumbnail_cover_image', models.ImageField(upload_to='')),
                ('enlarged_cover_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200, verbose_name='Source of tag')),
                ('add_date', models.DateTimeField(verbose_name='Date added')),
                ('update_date', models.DateTimeField(verbose_name='Date updated')),
                ('books', models.ManyToManyField(to='ebooks.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200, verbose_name='Source of rating')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('nb_ratings', models.PositiveIntegerField(verbose_name='Number of ratings')),
                ('add_date', models.DateTimeField(verbose_name='Date added')),
                ('update_date', models.DateTimeField(verbose_name='Date updated')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebooks.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200, verbose_name='Source of category')),
                ('add_date', models.DateTimeField(verbose_name='Date added')),
                ('update_date', models.DateTimeField(verbose_name='Date updated')),
                ('books', models.ManyToManyField(to='ebooks.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('add_date', models.DateTimeField(verbose_name='Date added')),
                ('update_date', models.DateTimeField(verbose_name='Date updated')),
                ('books', models.ManyToManyField(to='ebooks.Book')),
            ],
        ),
    ]
